rootProject.name = "grpc-java-sample"

include("helloworld")
include("future-stub")
include("async-stub")
include("server-stream")
include("client-stream")
include("bidirectional-stream")
include("interceptor")
include("stream-tracer")
include("log")
include("binlog")
include("retry-policy")
include("hedging-policy")
include("name-resolver")
include("load-balancer")
include("load-balancer")
include("health-check")
include("tls")
include("channelz")